void SET_k(int k);
int k_yield();
void equation_DISCARD(unsigned long **equation);
unsigned long *equation_ADD(unsigned long *first_equation, unsigned long *second_equation);
unsigned long *equation_MULTIPLY(unsigned long *equation, unsigned long multiplier);
unsigned long *equation_NEGATIVE(unsigned long *equation);
unsigned long *equation_SUBTRACT(unsigned long *first_equation, unsigned long *second_equation);
unsigned long equation_multiplier(unsigned long *first_equation, unsigned long *second_equation, int index);
unsigned long *coefficient_cancel(unsigned long *first_equation, unsigned long *second_equation, int index);
unsigned long **equations_ALLOCATE();
int equation_amount(unsigned long ***equation);
void equations_DELETE(unsigned long **equations);
unsigned long **coefficients_ALLOCATE();
