void equation_DISCARD(unsigned long **equation);
int equation_length(unsigned long **equation);
unsigned long **equation_initialize(int required_size);
unsigned long **equation_ADD(unsigned long **equation_ONE, unsigned long **equation_TWO);
unsigned long **equation_MULTIPLY(unsigned long **equation, unsigned long multiplier);
unsigned long **equation_NEGATIVE(unsigned long **equation);
unsigned long **equation_SUBTRACT(unsigned long **equation_ONE, unsigned long **equation_TWO);
void equation_DISPLAY(unsigned long **equation);
unsigned long equation_multiplier(unsigned long **equation_ONE, unsigned long **equation_TWO, int index);
unsigned long **coefficient_cancel(unsigned long **equation_ONE, unsigned long **equation_TWO, int index);
unsigned long ***equations_ALLOCATE(int k_in_k_N_SSSS);
