../mathematics/.maths.o: ../mathematics/maths.h ../mathematics/maths.c
	gcc -c ../mathematics/maths.c -o ../mathematics/.maths.o

.string.o: ../mathematics/.maths.o string.h string.c
	gcc -c string.c -o .string.o

.modular_groups.o: modular_groups.c
	gcc -c modular_groups.c -o .modular_groups.o
