../mathematics/.maths.o: ../mathematics/maths.c ../mathematics/maths.h
	gcc -c ../mathematics/maths.c -o ../mathematics/.maths.o

.string.o: ../mathematics/.maths.o string.c string.h
	gcc -c string.c -o .string.o
