../mathematics/.maths.o: ../mathematics/maths.h ../mathematics/maths.c
	gcc -c ../mathematics/maths.c -o ../mathematics/.maths.o

.string.o: ../mathematics/.maths.o string.h string.c
	gcc -c string.c -o .string.o
